spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/mighty_online_db?serverTimezone=Asia/Seoul
    username: mighty
    password: mightypw
    sql:
      init:
        mode: always
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

---
